export const WeatherTextName = [
  "Sunny",
  "Cloudy",
  "Overcast",
  "Shower rain",
  "Heavy shower rain",
  "Thundershower",
  "Heavy thunderstorm",
  "Storm",
  "Rain",
  "Light snow",
  "Moderate snow",
  "Heavy snow",
  "Snowstorm",
  "Sleet",
  "Rain and snow",
  "Shower snow",
  "Snow",
  "Mist",
  "Foggy",
  "Sandstorm",
  "Typhoon",
  "Tornado",
  "Rainstorm",
  "Frost",
  "Cold warning",
  "Medical meteorology",
  "Thunderstorm",
  "Flood",
  "Wind",
  "Snow ice",
  "Fog",
];

// export const FullWeatherTextName = [
//   "Sunny",
//   "Sunny fill",
//   "Cloudy",
//   "Cloudy fill",
//   "Few clouds",
//   "Few clouds fill",
//   "Partly cloudy",
//   "Partly cloudy fill",
//   "Overcast",
//   "Overcast fill",
//   "Clear night",
//   "Clear night fill",
//   "Cloudy night",
//   "Cloudy night fill",
//   "Few clouds night",
//   "Few clouds night fill",
//   "Partly cloudy night",
//   "Partly cloudy night fill",
//   "Shower rain",
//   "Shower rain fill",
//   "Heavy shower rain",
//   "Heavy shower rain fill",
//   "Thundershower",
//   "Thundershower fill",
//   "Heavy thunderstorm",
//   "Heavy thunderstorm fill",
//   "Thundershower with hail",
//   "Thundershower with hail fill",
//   "Light rain",
//   "Light rain fill",
//   "Moderate rain",
//   "Moderate rain fill",
//   "Heavy rain",
//   "Heavy rain fill",
//   "Extreme rain",
//   "Extreme rain fill",
//   "Drizzle rain",
//   "Drizzle rain fill",
//   "Storm",
//   "Storm fill",
//   "Heavy storm",
//   "Heavy storm fill",
//   "Severe storm",
//   "Severe storm fill",
//   "Freezing rain",
//   "Freezing rain fill",
//   "Light to moderate rain",
//   "Light to moderate rain fill",
//   "Moderate to heavy rain",
//   "Moderate to heavy rain fill",
//   "Heavy rain to storm",
//   "Heavy rain to storm fill",
//   "Storm to heavy storm",
//   "Storm to heavy storm fill",
//   "Heavy to severe storm",
//   "Heavy to severe storm fill",
//   "Shower rain night",
//   "Shower rain night fill",
//   "Heavy shower rain night",
//   "Heavy shower rain night fill",
//   "Rain",
//   "Rain fill",
//   "Light snow",
//   "Light snow fill",
//   "Moderate snow",
//   "Moderate snow fill",
//   "Heavy snow",
//   "Heavy snow fill",
//   "Snowstorm",
//   "Snowstorm fill",
//   "Sleet",
//   "Sleet fill",
//   "Rain and snow",
//   "Rain and snow fill",
//   "Shower snow",
//   "Shower snow fill",
//   "Snow flurry",
//   "Snow flurry fill",
//   "Light to moderate snow",
//   "Light to moderate snow fill",
//   "Moderate to heavy snow",
//   "Moderate to heavy snow fill",
//   "Heavy snow to snowstorm",
//   "Heavy snow to snowstorm fill",
//   "Shower snow night",
//   "Shower snow night fill",
//   "Snow flurry night",
//   "Snow flurry night fill",
//   "Snow",
//   "Snow fill",
//   "Mist",
//   "Mist fill",
//   "Foggy",
//   "Foggy fill",
//   "Haze",
//   "Haze fill",
//   "Sand",
//   "Sand fill",
//   "Dust",
//   "Dust fill",
//   "Duststorm",
//   "Duststorm fill",
//   "Sandstorm",
//   "Sandstorm fill",
//   "Dense fog",
//   "Dense fog fill",
//   "Strong fog",
//   "Strong fog fill",
//   "Moderate haze",
//   "Moderate haze fill",
//   "Heavy haze",
//   "Heavy haze fill",
//   "Severe haze",
//   "Severe haze fill",
//   "Heavy fog",
//   "Heavy fog fill",
//   "Extra heavy fog",
//   "Extra heavy fog fill",
//   "New moon",
//   "Waxing crescent",
//   "First quarter",
//   "Waxing gibbous",
//   "Full moon",
//   "Waning gibbous",
//   "Last quarter",
//   "Waning crescent",
//   "Hot",
//   "Hot fill",
//   "Cold",
//   "Cold fill",
//   "Unknown",
//   "Unknown fill",
//   "Typhoon",
//   "Tornado",
//   "Rainstorm",
//   "Snow storm",
//   "Cold wave",
//   "Gale",
//   "Sandstorm warning",
//   "Low temperature freeze",
//   "High temperature",
//   "Heat wave",
//   "Dry hot air",
//   "Downburst",
//   "Avalanche",
//   "Lightning",
//   "Hail",
//   "Frost",
//   "Heavy fog warning",
//   "Low level wind shearl",
//   "Haze warning",
//   "Thunder gust",
//   "Road icing",
//   "Drought",
//   "Gale at sea",
//   "Heat stroke",
//   "Wildfire",
//   "Grassland fire",
//   "Freeze",
//   "Space weather",
//   "Heavy air pollution",
//   "Low temperature rain and snow",
//   "Strong convection",
//   "Ozone",
//   "Heavy snow warning",
//   "Cold warning",
//   "Continuous rain",
//   "Waterlogging",
//   "Geological hazard",
//   "Heavy rainfall",
//   "Severely falling temperature",
//   "Snow disaster",
//   "Wildfire grassland",
//   "Medical meteorology",
//   "Thunderstorm",
//   "School closure",
//   "Factory closure",
//   "Maritime risk",
//   "Spring dust",
//   "Falling temperature",
//   "Typhoon and rainstorm",
//   "Severe cold",
//   "Sand dust",
//   "Sea thunderstorms",
//   "Sea fog",
//   "Sea thunder",
//   "Sea typhoon",
//   "Low temperature",
//   "Road ice and snow",
//   "Thunderstorm and gale",
//   "Continuous low temperature",
//   "Strong dust",
//   "Short lived heavy shower rain",
//   "Flood",
//   "Mudflow",
//   "Storm surge",
//   "Very hot weather",
//   "Strong monsoon signal",
//   "Landslip",
//   "Tropical cyclone",
//   "Fire danger",
//   "Flooding in the northern new territories",
//   "Cold weather",
//   "Wind",
//   "Snow ice",
//   "Fog",
//   "Coastal event",
//   "Forest fire",
//   "Rain warning",
//   "Rain flood",
//   "Freezing rain icing",
//   "Ground frost",
//   "Dust raising winds",
//   "Strong surface winds",
//   "Hot day",
//   "Warm night",
//   "Cold day",
//   "Thunderstorm and lightning",
//   "Hailstorm",
//   "Sea area warning",
//   "Fishermen warning",
//   "Low humidity",
//   "Accumulated rain",
//   "Hazardous surf warning",
//   "Marine wind warning",
//   "Road weather alert",
//   "Thunder rain",
//   "Thunder rain and fog",
//   "Damaging winds",
//   "Veld fire conditions",
//   "Weather advisory",
//   "Severe weather warning",
//   "Warning default"
// ]
