export const WeatherTextName = [
  "Sunny",
  "Cloudy",
  "Few clouds",
  "Partly cloudy",
  "Overcast",
  "Clear night",
  "Cloudy night",
  "Few clouds night",
  "Partly cloudy night",
  "Shower rain",
  "Heavy shower rain",
  "Thundershower",
  "Heavy thunderstorm",
  "Thundershower with hail",
  "Light rain",
  "Moderate rain",
  "Heavy rain",
  "Extreme rain",
  "Drizzle rain",
  "Storm",
  "Heavy storm",
  "Severe storm",
  "Freezing rain",
  "Light to moderate rain",
  "Moderate to heavy rain",
  "Heavy rain to storm",
  "Storm to heavy storm",
  "Heavy to severe storm",
  "Shower rain night",
  "Heavy shower rain night",
  "Rain",
  "Light snow",
  "Moderate snow",
  "Heavy snow",
  "Snowstorm",
  "Sleet",
  "Rain and snow",
  "Shower snow",
  "Snow flurry",
  "Light to moderate snow",
  "Moderate to heavy snow",
  "Heavy snow to snowstorm",
  "Shower snow night",
  "Snow flurry night",
  "Snow",
  "Mist",
  "Foggy",
  "Haze",
  "Sand",
  "Dust",
  "Duststorm",
  "Sandstorm",
  "Dense fog",
  "Strong fog",
  "Moderate haze",
  "Heavy haze",
  "Severe haze",
  "Heavy fog",
  "Extra heavy fog",
  "Hot",
  "Cold",
  "Unknown",
];
